### ISSUE TITLE
Panic on kratos-admin/recovery/link

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#1384]
**Describe the bug**

```
2021/05/28 10:42:42 http: panic serving 100.96.3.22:54040: runtime error: invalid memory address or nil pointer dereference
goroutine 1267 [running]:
net/http.(*conn).serve.func1(0xc000832320)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x14d3ac0, 0x221d5a0)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/ory/kratos/selfservice/strategy/link.(*Strategy).handleRecoveryError(0xc0004084b0, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a800, 0xc0003781e0, 0x0, 0x190fc40, 0xc00040bde8, 0xc00040bde8, 0xc000495008)
	/home/ory/selfservice/strategy/link/strategy_recovery.go:451 +0x110
github.com/ory/kratos/selfservice/strategy/link.(*Strategy).recoveryIssueSession(0xc0004084b0, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a800, 0xc0003781e0, 0x8a4362c47c2c2727, 0xa4fe711a16f7e5a1, 0x1, 0x16bcfda)
	/home/ory/selfservice/strategy/link/strategy_recovery.go:328 +0xab5
github.com/ory/kratos/selfservice/strategy/link.(*Strategy).recoveryUseToken(0xc0004084b0, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a800, 0xc00040e3c0, 0x4, 0x7f4764053150)
	/home/ory/selfservice/strategy/link/strategy_recovery.go:381 +0x419
github.com/ory/kratos/selfservice/strategy/link.(*Strategy).Recover(0xc0004084b0, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a800, 0xc0003780f0, 0xc0003780f0, 0x0)
	/home/ory/selfservice/strategy/link/strategy_recovery.go:281 +0x205
github.com/ory/kratos/selfservice/flow/recovery.(*Handler).submitFlow(0xc00048c770, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a800, 0x0, 0x0, 0x0)
	/home/ory/selfservice/flow/recovery/handler.go:303 +0x216
github.com/ory/kratos/session.(*Handler).IsNotAuthenticated.func1(0x7f4763ee2878, 0xc0004061f8, 0xc000f2a800, 0x0, 0x0, 0x0)
	/home/ory/session/handler.go:193 +0x48c
github.com/ory/kratos/x.NoCacheHandler.func1(0x7f4763ee2878, 0xc0004061f8, 0xc000f2a800, 0x0, 0x0, 0x0)
	/home/ory/x/nocache.go:18 +0x83
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0003e2120, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a800)
	/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xc7e
github.com/ory/nosurf.(*CSRFHandler).handleSuccess(...)
	/go/pkg/mod/github.com/ory/nosurf@v1.2.4/handler.go:199
github.com/ory/nosurf.(*CSRFHandler).ServeHTTP(0xc00025e000, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a700)
	/go/pkg/mod/github.com/ory/nosurf@v1.2.4/handler.go:150 +0x850
github.com/urfave/negroni.Wrap.func1(0x7f4763ee2878, 0xc0004061f8, 0xc000f2a700, 0xc00004e680)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc0003ea138, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a700, 0xc00004e680)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x1912d80, 0xc0003ea138, 0xc00040a078, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a700)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/ory/kratos/x.glob..func1(0x7f4763ee2878, 0xc0004061f8, 0xc000f2a700, 0xc00004e200)
	/home/ory/x/clean_url.go:12 +0x8b
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0x179c280, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a700, 0xc00004e200)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x1912d80, 0x179c280, 0xc00040a060, 0x7f4763ee2878, 0xc0004061f8, 0xc000f2a700)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0003da540, 0x192ec68, 0xc000ee8380, 0xc000f2a700)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96 +0xf1
github.com/gorilla/context.ClearHandler.func1(0x192ec68, 0xc000ee8380, 0xc000f2a700)
	/go/pkg/mod/github.com/gorilla/context@v1.1.1/context.go:141 +0x74
net/http.HandlerFunc.ServeHTTP(0xc00040a168, 0x192ec68, 0xc000ee8380, 0xc000f2a700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc000480000, 0x192ec68, 0xc000ee8380, 0xc000f2a700)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000832320, 0x1934df8, 0xc000096600)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

The problem clearly is in our code as here we just use the body

https://github.com/ory/kratos/blob/3c056461effa92bf3c067b6ffd80ee04d4046072/selfservice/strategy/link/strategy_recovery.go#L445-L453

but in many places we pass nil as the body, e.g.

https://github.com/ory/kratos/blob/3c056461effa92bf3c067b6ffd80ee04d4046072/selfservice/strategy/link/strategy_recovery.go#L328

**Expected behavior**

No panic

**Environment**

- Version: master, v0.6.3-alpha.1

**Additional context**

Initially reported here: https://ory-community.slack.com/archives/C012RJ2MQ1H/p1622199680084000

**Comment by slayer321** [comment]
Hey @zepatrik, I am new to open source and Golang and will like to contribute to this project, can you guide me on what needs to be done.

**Comment by zepatrik** [comment]
I recommend you investigate where the function is used and what the `body` is actually used for. Either check if it is not nil and do something else if it is, or make sure that it never is nil.

**Comment by aeneasr** [comment]
Not merged yet but closing so that noone starts working on this :)
