### ISSUE TITLE
Versions 0.6.x of the ruby gem contains syntactically invalid code

### ISSUE THREAD

**Issue by filterfish** [ory/kratos#1426]
**Describe the bug**

Line 200 (version 0.6.3.alpha1) of `lib/ory-kratos-client/configuration.rb contains a syntax error. 

**Reproducing the bug**

Steps to reproduce the behaviour:

Create a `Gemfile` containing the following:

```
source 'https://rubygems.org'

gem 'ory-kratos-client',        '= 0.6.3.alpha1'
```

then run:

```bash
bundle install
bundle exec ruby -e 'require "ory-kratos-client"'
```
and the following error is raised:

```
/home/rgh/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:232: warning: One-line pattern matching is experimental, and the behavior may change in future versions of Ruby!
/home/rgh/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client.rb:17:in `require': /home/rgh/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:228: syntax error, unexpected ',' (SyntaxError)
            in: ,
                ^
/home/rgh/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:229: syntax error, unexpected ',', expecting `end'
...     key: 'ory_kratos_session',
...                              ^
/home/rgh/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:231: syntax error, unexpected '}', expecting `end'
          },
          ^
/home/rgh/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:238: syntax error, unexpected ',', expecting `end'
          },
           ^
/home/rgh/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client/configuration.rb:291: syntax error, unexpected end-of-input, expecting `end'
        from /home/rgh/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/ory-kratos-client-0.6.3.alpha1/lib/ory-kratos-client.rb:17:in `<top (required)>'
        from -e:1:in `require'
        from -e:1:in `<main>'
```

**Expected behavior**

Not to raise an error!

**Environment**

Versions:
  ruby: 3.0.1
  ory-kratos-client: 0.6.3.alpha1

The same error is raised for all versions in the `0.6.*` gems and with version 2.7.2 of ruby.
Version `0.4.*` works as expected.

**Additional context**

The offending code is this method:

```ruby
    def auth_settings
      {
        ...
        'sessionCookie' =>
          {
            type: 'api_key',
            in: ,
            key: 'ory_kratos_session',
            value: api_key_with_prefix('sessionCookie')
          },
        ...
      }
    end
```

I've tried setting different values for `in:` such as `header` or `cookie` and whilst it stops the error message I still couldn't get it to work.

**Comment by aeneasr** [comment]
This looks like a bug with the generator and should be fixed upstream: https://github.com/OpenAPITools/openapi-generator/issues.

All we could do on our end would be to remove the `sessionCookie` security definition :/

**Comment by aeneasr** [comment]
https://github.com/OpenAPITools/openapi-generator/issues/6959
