### ISSUE TITLE
Kratos web_hook not working

### ISSUE THREAD

**Issue by pprus** [ory/kratos#2191]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'm using single page app with kratos as a server.

When i add custom web_hook to registration flow make a request to my node app i get an error.

### Reproducing the bug

1. Download this repo: https://github.com/ory/kratos-selfservice-ui-react-nextjs
2. run npm install and run npm run dev
3. then fetch kratos server and run it as it is described here: https://www.ory.sh/nextjs-authentication-spa-custom-flows-open-source/
```git clone --depth 1 --branch master https://github.com/ory/kratos.git
cd kratos
git checkout master
git pull -ff
docker-compose -f quickstart.yml -f contrib/quickstart/kratos/cloud/quickstart.yml up --build --force-recreate -d
```

4. Add custom web_hook to registration flow or any other

```
  flows:
    error:
      ui_url: http://localhost:3000/error

    settings:
      ui_url: http://localhost:3000/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://localhost:3000/recovery

    verification:
      enabled: true
      ui_url: http://localhost:3000/verification
      after:
        default_browser_return_url: http://localhost:3000

    logout:
      after:
        default_browser_return_url: http://localhost:3000/login

    login:
      ui_url: http://localhost:3000/login
      after:
        password:
          hooks:
            - hook: revoke_active_sessions
            - hook: require_verified_address

    registration:
      ui_url: http://localhost:3000/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: web_hook
              config:
                url: http://192.168.0.157:3002
                method: 'GET'
 
```

5. In my case try to register

I'm getting the following error output
 

### Relevant log output

```shell
kratos_1                      | time=2022-02-03T20:46:11Z level=debug msg=ExecutePostRegistrationPostPersistHook completed successfully. func=github.com/ory/kratos/selfservice/flow/registration.(*HookExecutor).PostRegistrationHook file=/home/ory/selfservice/flow/registration/hook.go:177 audience=application executor=*hook.Verifier executor_position=0 executors=[*hook.Verifier *hook.SessionIssuer *hook.WebHook] flow_method=password http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate accept-language:en-US,en;q=0.9 content-length:238 content-type:application/json cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". origin:http://localhost:3000 referer:http://localhost:3000/registration?flow=af151cf7-7eac-4edd-9731-6a7dcb4fb979 sec-ch-ua:" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96" sec-ch-ua-mobile:?0 sec-ch-ua-platform:"Linux" sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-origin user-agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 x-forwarded-for:172.25.0.1 x-forwarded-proto:http] host:localhost:4455 method:POST path:/self-service/registration query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:172.25.0.3:58712 scheme:http] identity_id=dc4e49d2-aebc-4b68-9a41-d7fce4ee40de service_name=Ory Kratos service_version=v0.8.0-alpha.3
kratos_1                      | time=2022-02-03T20:46:11Z level=debug msg=ExecutePostRegistrationPostPersistHook completed successfully. func=github.com/ory/kratos/selfservice/flow/registration.(*HookExecutor).PostRegistrationHook file=/home/ory/selfservice/flow/registration/hook.go:177 audience=application executor=*hook.SessionIssuer executor_position=1 executors=[*hook.Verifier *hook.SessionIssuer *hook.WebHook] flow_method=password http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate accept-language:en-US,en;q=0.9 content-length:238 content-type:application/json cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". origin:http://localhost:3000 referer:http://localhost:3000/registration?flow=af151cf7-7eac-4edd-9731-6a7dcb4fb979 sec-ch-ua:" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96" sec-ch-ua-mobile:?0 sec-ch-ua-platform:"Linux" sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-origin user-agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 x-forwarded-for:172.25.0.1 x-forwarded-proto:http] host:localhost:4455 method:POST path:/self-service/registration query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:172.25.0.3:58712 scheme:http] identity_id=dc4e49d2-aebc-4b68-9a41-d7fce4ee40de service_name=Ory Kratos service_version=v0.8.0-alpha.3
kratos_1                      | 2022/02/03 20:46:11 http: panic serving 172.25.0.3:58712: runtime error: invalid memory address or nil pointer dereference
kratos_1                      | goroutine 62 [running]:
kratos_1                      | net/http.(*conn).serve.func1()
kratos_1                      | 	/usr/local/go/src/net/http/server.go:1801 +0xb9
kratos_1                      | panic({0x155fa00, 0x24c5190})
kratos_1                      | 	/usr/local/go/src/runtime/panic.go:1047 +0x266
kratos_1                      | bytes.(*Reader).Len(...)
kratos_1                      | 	/usr/local/go/src/bytes/reader.go:27
kratos_1                      | net/http.NewRequestWithContext({0x1a48568, 0xc000044040}, {0xc0003ff2d8, 0xc000d3e598}, {0xc000fb2100, 0x19}, {0x1a1bc00, 0x0})
kratos_1                      | 	/usr/local/go/src/net/http/request.go:899 +0x464
kratos_1                      | net/http.NewRequest(...)
kratos_1                      | 	/usr/local/go/src/net/http/request.go:830
kratos_1                      | github.com/ory/kratos/selfservice/hook.doHttpCall({0xc0003ff2d8, 0x0}, {0xc000fb2100, 0xc000600400}, {0x1a1cf80, 0x277fde0}, {0x1a1bc00, 0x0})
kratos_1                      | 	/home/ory/selfservice/hook/web_hook.go:311 +0x76
kratos_1                      | github.com/ory/kratos/selfservice/hook.(*WebHook).execute(0xc000d167b0, 0xc000d63a00)
kratos_1                      | 	/home/ory/selfservice/hook/web_hook.go:266 +0x14e
kratos_1                      | github.com/ory/kratos/selfservice/hook.(*WebHook).ExecutePostRegistrationPostPersistHook(0xc0005bb9d0, {0x5, 0xc000d3e778}, 0xc000726c00, 0xc000db6000, 0xc000e2a000)
kratos_1                      | 	/home/ory/selfservice/hook/web_hook.go:229 +0x106
kratos_1                      | github.com/ory/kratos/selfservice/flow/registration.(*HookExecutor).PostRegistrationHook(0xc000c32d00, {0x7f5c9901ecc0, 0xc000edce60}, 0xc000726c00, {0x17585f4, 0x8}, 0xc000db6000, 0xc000d1a2a0)
kratos_1                      | 	/home/ory/selfservice/flow/registration/hook.go:156 +0xb7b
kratos_1                      | github.com/ory/kratos/selfservice/flow/registration.(*Handler).submitFlow(0xc0006908e0, {0x7f5c9901ecc0, 0xc000edce60}, 0xc000726c00, {0x10, 0x0, 0x0})
kratos_1                      | 	/home/ory/selfservice/flow/registration/handler.go:449 +0x518
kratos_1                      | github.com/ory/kratos/session.(*Handler).IsNotAuthenticated.func1({0x7f5c9901ecc0, 0xc000edce60}, 0xc000726c00, {0x0, 0x0, 0x0})
kratos_1                      | 	/home/ory/session/handler.go:249 +0x390
kratos_1                      | github.com/ory/kratos/x.NoCacheHandler.func1({0x7f5c9901ecc0, 0xc000edce60}, 0xc00071e6c0, {0x0, 0x0, 0x0})
kratos_1                      | 	/home/ory/x/nocache.go:18 +0x71
kratos_1                      | github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0006bfe60, {0x7f5c9901ecc0, 0xc000edce60}, 0xc000726c00)
kratos_1                      | 	/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x84b
kratos_1                      | github.com/ory/nosurf.(*CSRFHandler).handleSuccess(...)
kratos_1                      | 	/go/pkg/mod/github.com/ory/nosurf@v1.2.5/handler.go:201
kratos_1                      | github.com/ory/nosurf.(*CSRFHandler).ServeHTTP(0xc000508580, {0x7f5c9901ecc0, 0xc000edce60}, 0xc000d540e0)
kratos_1                      | 	/go/pkg/mod/github.com/ory/nosurf@v1.2.5/handler.go:152 +0x6ac
kratos_1                      | github.com/urfave/negroni.Wrap.func1({0x7f5c9901ecc0, 0xc000edce60}, 0x15b7b60, 0xc000d540e0)
kratos_1                      | 	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x4b
kratos_1                      | github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc000d540c0, {0x7f5c9901ecc0, 0xc000edce60}, 0x0, 0xc000d17038)
kratos_1                      | 	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x33
kratos_1                      | github.com/urfave/negroni.middleware.ServeHTTP({{0x1a20b40, 0xc0004a1158}, 0xc0004a11d0}, {0x7f5c9901ecc0, 0xc000edce60}, 0x0)
kratos_1                      | 	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0xb6
kratos_1                      | github.com/ory/kratos/x.glob..func1({0x7f5c9901ecc0, 0xc000edce60}, 0xc000726800, 0xc000d540c0)
kratos_1                      | 	/home/ory/x/clean_url.go:12 +0x79
kratos_1                      | github.com/urfave/negroni.HandlerFunc.ServeHTTP(0x1a52058, {0x7f5c9901ecc0, 0xc000edce60}, 0x1a20840, 0xc00073d590)
kratos_1                      | 	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x33
kratos_1                      | github.com/urfave/negroni.middleware.ServeHTTP({{0x1a20b40, 0x1873bf0}, 0xc0004a11b8}, {0x7f5c9901ecc0, 0xc000edce60}, 0xc000d17138)
kratos_1                      | 	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0xb6
kratos_1                      | net/http.HandlerFunc.ServeHTTP(0x7f5c9901ecc0, {0x7f5c9901ecc0, 0xc000edce60}, 0x1a20800)
kratos_1                      | 	/usr/local/go/src/net/http/server.go:2046 +0x2f
kratos_1                      | github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1({0x7f5c9901ecc0, 0xc000edce10}, 0xc000726800)
kratos_1                      | 	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:198 +0xa3
kratos_1                      | net/http.HandlerFunc.ServeHTTP(0x7f5c9901ecc0, {0x7f5c9901ecc0, 0xc000edce10}, 0xc00073d530)
kratos_1                      | 	/usr/local/go/src/net/http/server.go:2046 +0x2f
kratos_1                      | github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x7f5c9901ecc0, 0xc000edcdc0}, 0xc000726800)
kratos_1                      | 	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:101 +0x92
kratos_1                      | net/http.HandlerFunc.ServeHTTP(0x7f5c9901ecc0, {0x7f5c9901ecc0, 0xc000edcdc0}, 0x48)
kratos_1                      | 	/usr/local/go/src/net/http/server.go:2046 +0x2f
kratos_1                      | github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1({0x7f5c9901ecc0, 0xc000edcd70}, 0xc000726800)
kratos_1                      | 	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:68 +0xe3
kratos_1                      | net/http.HandlerFunc.ServeHTTP(0x1a20840, {0x7f5c9901ecc0, 0xc000edcd70}, 0xc00073d500)
kratos_1                      | 	/usr/local/go/src/net/http/server.go:2046 +0x2f
kratos_1                      | github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x7f5c9901ecc0, 0xc000edcd70}, 0xc000726800)
kratos_1                      | 	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:76 +0xa2
kratos_1                      | net/http.HandlerFunc.ServeHTTP(0x7f5c9901eaa0, {0x7f5c9901ecc0, 0xc000edcd70}, 0xc0002ca1c0)
kratos_1                      | 	/usr/local/go/src/net/http/server.go:2046 +0x2f
kratos_1                      | github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1({0x7f5c9901eaa0, 0xc000486550}, 0xc000726800)
kratos_1                      | 	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:165 +0xa3
kratos_1                      | net/http.HandlerFunc.ServeHTTP(0x0, {0x7f5c9901eaa0, 0xc000486550}, 0x0)
kratos_1                      | 	/usr/local/go/src/net/http/server.go:2046 +0x2f
kratos_1                      | github.com/ory/x/prometheusx.Metrics.instrumentHandlerStatusBucket.func1({0x7f5c9901eaa0, 0xc000486550}, 0xc000726800)
kratos_1                      | 	/go/pkg/mod/github.com/ory/x@v0.0.300/prometheusx/metrics.go:107 +0x4c
kratos_1                      | net/http.HandlerFunc.ServeHTTP(0x0, {0x7f5c9901eaa0, 0xc000486550}, 0x0)
kratos_1                      | 	/usr/local/go/src/net/http/server.go:2046 +0x2f
kratos_1                      | github.com/ory/x/prometheusx.(*MetricsManager).ServeHTTP(0xc0006bc200, {0x7f5c9901eaa0, 0xc000486550}, 0xc000d17658, 0x487a7b)
kratos_1                      | 	/go/pkg/mod/github.com/ory/x@v0.0.300/prometheusx/middleware.go:30 +0xf3
kratos_1                      | github.com/urfave/negroni.middleware.ServeHTTP({{0x1a1d120, 0xc0006bc200}, 0xc0004a11a0}, {0x7f5c9901eaa0, 0xc000486550}, 0x493837)
kratos_1                      | 	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0xb6
kratos_1                      | github.com/ory/x/metricsx.(*Service).ServeHTTP(0xc000edc050, {0x7f5c9901eaa0, 0xc000486550}, 0xc000726800, 0xc000547f40)
kratos_1                      | 	/go/pkg/mod/github.com/ory/x@v0.0.300/metricsx/middleware.go:255 +0xb9
kratos_1                      | github.com/urfave/negroni.middleware.ServeHTTP({{0x1a1d0e0, 0xc000edc050}, 0xc0004a1188}, {0x7f5c9901eaa0, 0xc000486550}, 0x18)
kratos_1                      | 	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0xb6
kratos_1                      | github.com/ory/x/reqlog.(*Middleware).ServeHTTP(0xc000b52000, {0x7f5c9901eaa0, 0xc000486550}, 0xc000726800, 0xc000547ee0)
kratos_1                      | 	/go/pkg/mod/github.com/ory/x@v0.0.300/reqlog/middleware.go:134 +0x395
kratos_1                      | github.com/urfave/negroni.middleware.ServeHTTP({{0x1a1d140, 0xc000b52000}, 0xc0004a1170}, {0x7f5c9901eaa0, 0xc000486550}, 0xc000d1e040)
kratos_1                      | 	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0xb6
kratos_1                      | github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0004b9e60, {0x1a36398, 0xc000d1a000}, 0xc000726800)
kratos_1                      | 	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96 +0x110
kratos_1                      | github.com/rs/cors.(*Cors).Handler.func1({0x1a36398, 0xc000d1a000}, 0xc000726800)
kratos_1                      | 	/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1bd
kratos_1                      | net/http.HandlerFunc.ServeHTTP(0xc00071e6e0, {0x1a36398, 0xc000d1a000}, 0x7f5cc00f5a68)
kratos_1                      | 	/usr/local/go/src/net/http/server.go:2046 +0x2f
kratos_1                      | net/http.serverHandler.ServeHTTP({0x1a30370}, {0x1a36398, 0xc000d1a000}, 0xc000726800)
kratos_1                      | 	/usr/local/go/src/net/http/server.go:2878 +0x43b
kratos_1                      | net/http.(*conn).serve(0xc0005a43c0, {0x1a485d8, 0xc000a4c4b0})
kratos_1                      | 	/usr/local/go/src/net/http/server.go:1929 +0xb08
kratos_1                      | created by net/http.(*Server).Serve
kratos_1                      | 	/usr/local/go/src/net/http/server.go:3033 +0x4e8
```

### Version

oryd/kratos v0.8.2-alpha.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by dnlsndr** [comment]
Same here :wave:

**Comment by aeneasr** [comment]
Thank you for the report! Any contributions towards fixing this are highly appreciated!

**Comment by delfzzz** [comment]
@pprus although the `body` was marked in the doc as optional https://www.ory.sh/docs/kratos/self-service/hooks#web-hooks, have you tried supplying it? even a very basic one? might be a quick fix for this issue.

**Comment by PhilipKuchelmeister** [comment]
@delfzzz 
Thank you for your hint. We have tried this, it does not fix the isses. (Having the same problems)

**Comment by aeneasr** [comment]
This has been resolved on master - requests without body now either fail with an error message or where a body is not needed will ignore the parameter. Thank you for the reports!
