### ISSUE TITLE
Ory Kratos quickstart error

### ISSUE THREAD

**Issue by JackySu** [ory/kratos#4094]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

I followed the instructions on https://www.ory.sh/docs/kratos/quickstart and use docker to run an example with
```shell
git clone https://github.com/ory/kratos.git
cd kratos
git checkout master
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate
```
http://127.0.0.1:4455 works for me
![image](https://github.com/user-attachments/assets/4c62b4db-d9d9-45be-8e06-79bf1032ee27)
but when I click sign in I get
![image](https://github.com/user-attachments/assets/3598ae3a-e8d2-47c2-98b3-f5b49c2c4a27)
the same error occurs for any other button like sign up

### Reproducing the bug

```shell
git clone https://github.com/ory/kratos.git
cd kratos
git checkout master
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate
```
go to http://127.0.0.1:4455 and click login

### Relevant log output

```shell
kratos-selfservice-ui-node-1  | AxiosError: Request failed with status code 502
kratos-selfservice-ui-node-1  |     at settle (/usr/src/app/node_modules/axios/dist/node/axios.cjs:1967:12)
kratos-selfservice-ui-node-1  |     at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/dist/node/axios.cjs:3066:11)
kratos-selfservice-ui-node-1  |     at IncomingMessage.emit (node:events:525:35)
kratos-selfservice-ui-node-1  |     at endReadableNT (node:internal/streams/readable:1359:12)
kratos-selfservice-ui-node-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
kratos-selfservice-ui-node-1  |     at Axios.request (/usr/src/app/node_modules/axios/dist/node/axios.cjs:3877:41)
kratos-selfservice-ui-node-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
kratos-selfservice-ui-node-1  |   code: 'ERR_BAD_RESPONSE',
kratos-selfservice-ui-node-1  |   config: {
kratos-selfservice-ui-node-1  |     transitional: {
kratos-selfservice-ui-node-1  |       silentJSONParsing: true,
kratos-selfservice-ui-node-1  |       forcedJSONParsing: true,
kratos-selfservice-ui-node-1  |       clarifyTimeoutError: false
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     adapter: [ 'xhr', 'http' ],
kratos-selfservice-ui-node-1  |     transformRequest: [ [Function: transformRequest] ],
kratos-selfservice-ui-node-1  |     transformResponse: [ [Function: transformResponse] ],
kratos-selfservice-ui-node-1  |     timeout: 0,
kratos-selfservice-ui-node-1  |     xsrfCookieName: 'XSRF-TOKEN',
kratos-selfservice-ui-node-1  |     xsrfHeaderName: 'X-XSRF-TOKEN',
kratos-selfservice-ui-node-1  |     maxContentLength: -1,
kratos-selfservice-ui-node-1  |     maxBodyLength: -1,
kratos-selfservice-ui-node-1  |     env: { FormData: [Function], Blob: [class Blob] },
kratos-selfservice-ui-node-1  |     validateStatus: [Function: validateStatus],
kratos-selfservice-ui-node-1  |     headers: Object [AxiosHeaders] {
kratos-selfservice-ui-node-1  |       Accept: 'application/json, text/plain, */*',
kratos-selfservice-ui-node-1  |       'Content-Type': undefined,
kratos-selfservice-ui-node-1  |       Cookie: 'csrf_token_806060ca5bf70dff3caa0e5c860002aade9d470a5a4dce73bcfa7ba10778f481=Uq2FJ3J4k+B+3S1s/qeG1XiAiGXVuCPYAjxP2g4WoqA=',
kratos-selfservice-ui-node-1  |       'User-Agent': 'axios/1.6.7',
kratos-selfservice-ui-node-1  |       'Accept-Encoding': 'gzip, compress, deflate, br'
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     method: 'get',
kratos-selfservice-ui-node-1  |     url: 'http://kratos:4433//self-service/login/flows?id=e756d2cc-dd3d-492e-b697-c82e7661515f',
kratos-selfservice-ui-node-1  |     data: undefined
kratos-selfservice-ui-node-1  |   },
kratos-selfservice-ui-node-1  |   request: <ref *1> ClientRequest {
kratos-selfservice-ui-node-1  |     _events: [Object: null prototype] {
kratos-selfservice-ui-node-1  |       abort: [Function (anonymous)],
kratos-selfservice-ui-node-1  |       aborted: [Function (anonymous)],
kratos-selfservice-ui-node-1  |       connect: [Function (anonymous)],
kratos-selfservice-ui-node-1  |       error: [Function (anonymous)],
kratos-selfservice-ui-node-1  |       socket: [Function (anonymous)],
kratos-selfservice-ui-node-1  |       timeout: [Function (anonymous)],
kratos-selfservice-ui-node-1  |       finish: [Function: requestOnFinish]
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     _eventsCount: 7,
kratos-selfservice-ui-node-1  |     _maxListeners: undefined,
kratos-selfservice-ui-node-1  |     outputData: [],
kratos-selfservice-ui-node-1  |     outputSize: 0,
kratos-selfservice-ui-node-1  |     writable: true,
kratos-selfservice-ui-node-1  |     destroyed: false,
kratos-selfservice-ui-node-1  |     _last: true,
kratos-selfservice-ui-node-1  |     chunkedEncoding: false,
kratos-selfservice-ui-node-1  |     shouldKeepAlive: false,
kratos-selfservice-ui-node-1  |     maxRequestsOnConnectionReached: false,
kratos-selfservice-ui-node-1  |     _defaultKeepAlive: true,
kratos-selfservice-ui-node-1  |     useChunkedEncodingByDefault: false,
kratos-selfservice-ui-node-1  |     sendDate: false,
kratos-selfservice-ui-node-1  |     _removedConnection: false,
kratos-selfservice-ui-node-1  |     _removedContLen: false,
kratos-selfservice-ui-node-1  |     _removedTE: false,
kratos-selfservice-ui-node-1  |     strictContentLength: false,
kratos-selfservice-ui-node-1  |     _contentLength: 0,
kratos-selfservice-ui-node-1  |     _hasBody: true,
kratos-selfservice-ui-node-1  |     _trailer: '',
kratos-selfservice-ui-node-1  |     finished: true,
kratos-selfservice-ui-node-1  |     _headerSent: true,
kratos-selfservice-ui-node-1  |     _closed: false,
kratos-selfservice-ui-node-1  |     socket: Socket {
kratos-selfservice-ui-node-1  |       connecting: false,
kratos-selfservice-ui-node-1  |       _hadError: false,
kratos-selfservice-ui-node-1  |       _parent: null,
kratos-selfservice-ui-node-1  |       _host: null,
kratos-selfservice-ui-node-1  |       _closeAfterHandlingError: false,
kratos-selfservice-ui-node-1  |       _readableState: [ReadableState],
kratos-selfservice-ui-node-1  |       _events: [Object: null prototype],
kratos-selfservice-ui-node-1  |       _eventsCount: 7,
kratos-selfservice-ui-node-1  |       _maxListeners: undefined,
kratos-selfservice-ui-node-1  |       _writableState: [WritableState],
kratos-selfservice-ui-node-1  |       allowHalfOpen: false,
kratos-selfservice-ui-node-1  |       _sockname: null,
kratos-selfservice-ui-node-1  |       _pendingData: null,
kratos-selfservice-ui-node-1  |       _pendingEncoding: '',
kratos-selfservice-ui-node-1  |       server: null,
kratos-selfservice-ui-node-1  |       _server: null,
kratos-selfservice-ui-node-1  |       parser: null,
kratos-selfservice-ui-node-1  |       _httpMessage: [Circular *1],
kratos-selfservice-ui-node-1  |       [Symbol(async_id_symbol)]: 788,
kratos-selfservice-ui-node-1  |       [Symbol(kHandle)]: [TCP],
kratos-selfservice-ui-node-1  |       [Symbol(lastWriteQueueSize)]: 0,
kratos-selfservice-ui-node-1  |       [Symbol(timeout)]: null,
kratos-selfservice-ui-node-1  |       [Symbol(kBuffer)]: null,
kratos-selfservice-ui-node-1  |       [Symbol(kBufferCb)]: null,
kratos-selfservice-ui-node-1  |       [Symbol(kBufferGen)]: null,
kratos-selfservice-ui-node-1  |       [Symbol(kCapture)]: false,
kratos-selfservice-ui-node-1  |       [Symbol(kSetNoDelay)]: true,
kratos-selfservice-ui-node-1  |       [Symbol(kSetKeepAlive)]: true,
kratos-selfservice-ui-node-1  |       [Symbol(kSetKeepAliveInitialDelay)]: 60,
kratos-selfservice-ui-node-1  |       [Symbol(kBytesRead)]: 0,
kratos-selfservice-ui-node-1  |       [Symbol(kBytesWritten)]: 0
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     _header: 'GET http://kratos:4433//self-service/login/flows?id=e756d2cc-dd3d-492e-b697-c82e7661515f HTTP/1.1\r\n' +
kratos-selfservice-ui-node-1  |       'Accept: application/json, text/plain, */*\r\n' +
kratos-selfservice-ui-node-1  |       'Cookie: csrf_token_806060ca5bf70dff3caa0e5c860002aade9d470a5a4dce73bcfa7ba10778f481=Uq2FJ3J4k+B+3S1s/qeG1XiAiGXVuCPYAjxP2g4WoqA=\r\n' +
kratos-selfservice-ui-node-1  |       'User-Agent: axios/1.6.7\r\n' +
kratos-selfservice-ui-node-1  |       'Accept-Encoding: gzip, compress, deflate, br\r\n' +
kratos-selfservice-ui-node-1  |       'host: kratos:4433\r\n' +
kratos-selfservice-ui-node-1  |       'Connection: close\r\n' +
kratos-selfservice-ui-node-1  |       '\r\n',
kratos-selfservice-ui-node-1  |     _keepAliveTimeout: 0,
kratos-selfservice-ui-node-1  |     _onPendingData: [Function: nop],
kratos-selfservice-ui-node-1  |     agent: Agent {
kratos-selfservice-ui-node-1  |       _events: [Object: null prototype],
kratos-selfservice-ui-node-1  |       _eventsCount: 2,
kratos-selfservice-ui-node-1  |       _maxListeners: undefined,
kratos-selfservice-ui-node-1  |       defaultPort: 80,
kratos-selfservice-ui-node-1  |       protocol: 'http:',
kratos-selfservice-ui-node-1  |       options: [Object: null prototype],
kratos-selfservice-ui-node-1  |       requests: [Object: null prototype] {},
kratos-selfservice-ui-node-1  |       sockets: [Object: null prototype],
kratos-selfservice-ui-node-1  |       freeSockets: [Object: null prototype] {},
kratos-selfservice-ui-node-1  |       keepAliveMsecs: 1000,
kratos-selfservice-ui-node-1  |       keepAlive: false,
kratos-selfservice-ui-node-1  |       maxSockets: Infinity,
kratos-selfservice-ui-node-1  |       maxFreeSockets: 256,
kratos-selfservice-ui-node-1  |       scheduling: 'lifo',
kratos-selfservice-ui-node-1  |       maxTotalSockets: Infinity,
kratos-selfservice-ui-node-1  |       totalSocketCount: 1,
kratos-selfservice-ui-node-1  |       [Symbol(kCapture)]: false
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     socketPath: undefined,
kratos-selfservice-ui-node-1  |     method: 'GET',
kratos-selfservice-ui-node-1  |     maxHeaderSize: undefined,
kratos-selfservice-ui-node-1  |     insecureHTTPParser: undefined,
kratos-selfservice-ui-node-1  |     path: 'http://kratos:4433//self-service/login/flows?id=e756d2cc-dd3d-492e-b697-c82e7661515f',
kratos-selfservice-ui-node-1  |     _ended: true,
kratos-selfservice-ui-node-1  |     res: IncomingMessage {
kratos-selfservice-ui-node-1  |       _readableState: [ReadableState],
kratos-selfservice-ui-node-1  |       _events: [Object: null prototype],
kratos-selfservice-ui-node-1  |       _eventsCount: 4,
kratos-selfservice-ui-node-1  |       _maxListeners: undefined,
kratos-selfservice-ui-node-1  |       socket: [Socket],
kratos-selfservice-ui-node-1  |       httpVersionMajor: 1,
kratos-selfservice-ui-node-1  |       httpVersionMinor: 1,
kratos-selfservice-ui-node-1  |       httpVersion: '1.1',
kratos-selfservice-ui-node-1  |       complete: true,
kratos-selfservice-ui-node-1  |       rawHeaders: [Array],
kratos-selfservice-ui-node-1  |       rawTrailers: [],
kratos-selfservice-ui-node-1  |       aborted: false,
kratos-selfservice-ui-node-1  |       upgrade: false,
kratos-selfservice-ui-node-1  |       url: '',
kratos-selfservice-ui-node-1  |       method: null,
kratos-selfservice-ui-node-1  |       statusCode: 502,
kratos-selfservice-ui-node-1  |       statusMessage: 'Bad Gateway',
kratos-selfservice-ui-node-1  |       client: [Socket],
kratos-selfservice-ui-node-1  |       _consuming: false,
kratos-selfservice-ui-node-1  |       _dumped: false,
kratos-selfservice-ui-node-1  |       req: [Circular *1],
kratos-selfservice-ui-node-1  |       responseUrl: 'http://kratos:4433//self-service/login/flows?id=e756d2cc-dd3d-492e-b697-c82e7661515f',
kratos-selfservice-ui-node-1  |       redirects: [],
kratos-selfservice-ui-node-1  |       [Symbol(kCapture)]: false,
kratos-selfservice-ui-node-1  |       [Symbol(kHeaders)]: [Object],
kratos-selfservice-ui-node-1  |       [Symbol(kHeadersCount)]: 4,
kratos-selfservice-ui-node-1  |       [Symbol(kTrailers)]: null,
kratos-selfservice-ui-node-1  |       [Symbol(kTrailersCount)]: 0
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     aborted: false,
kratos-selfservice-ui-node-1  |     timeoutCb: null,
kratos-selfservice-ui-node-1  |     upgradeOrConnect: false,
kratos-selfservice-ui-node-1  |     parser: null,
kratos-selfservice-ui-node-1  |     maxHeadersCount: null,
kratos-selfservice-ui-node-1  |     reusedSocket: false,
kratos-selfservice-ui-node-1  |     host: '192.168.0.111',
kratos-selfservice-ui-node-1  |     protocol: 'http:',
kratos-selfservice-ui-node-1  |     _redirectable: Writable {
kratos-selfservice-ui-node-1  |       _writableState: [WritableState],
kratos-selfservice-ui-node-1  |       _events: [Object: null prototype],
kratos-selfservice-ui-node-1  |       _eventsCount: 3,
kratos-selfservice-ui-node-1  |       _maxListeners: undefined,
kratos-selfservice-ui-node-1  |       _options: [Object],
kratos-selfservice-ui-node-1  |       _ended: true,
kratos-selfservice-ui-node-1  |       _ending: true,
kratos-selfservice-ui-node-1  |       _redirectCount: 0,
kratos-selfservice-ui-node-1  |       _redirects: [],
kratos-selfservice-ui-node-1  |       _requestBodyLength: 0,
kratos-selfservice-ui-node-1  |       _requestBodyBuffers: [],
kratos-selfservice-ui-node-1  |       _onNativeResponse: [Function (anonymous)],
kratos-selfservice-ui-node-1  |       _currentRequest: [Circular *1],
kratos-selfservice-ui-node-1  |       _currentUrl: 'http://kratos:4433//self-service/login/flows?id=e756d2cc-dd3d-492e-b697-c82e7661515f',
kratos-selfservice-ui-node-1  |       [Symbol(kCapture)]: false
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     [Symbol(kCapture)]: false,
kratos-selfservice-ui-node-1  |     [Symbol(kBytesWritten)]: 0,
kratos-selfservice-ui-node-1  |     [Symbol(kEndCalled)]: true,
kratos-selfservice-ui-node-1  |     [Symbol(kNeedDrain)]: false,
kratos-selfservice-ui-node-1  |     [Symbol(corked)]: 0,
kratos-selfservice-ui-node-1  |     [Symbol(kOutHeaders)]: [Object: null prototype] {
kratos-selfservice-ui-node-1  |       accept: [Array],
kratos-selfservice-ui-node-1  |       cookie: [Array],
kratos-selfservice-ui-node-1  |       'user-agent': [Array],
kratos-selfservice-ui-node-1  |       'accept-encoding': [Array],
kratos-selfservice-ui-node-1  |       host: [Array]
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     [Symbol(kUniqueHeaders)]: null
kratos-selfservice-ui-node-1  |   },
kratos-selfservice-ui-node-1  |   response: {
kratos-selfservice-ui-node-1  |     status: 502,
kratos-selfservice-ui-node-1  |     statusText: 'Bad Gateway',
kratos-selfservice-ui-node-1  |     headers: Object [AxiosHeaders] {
kratos-selfservice-ui-node-1  |       connection: 'close',
kratos-selfservice-ui-node-1  |       'content-length': '0'
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     config: {
kratos-selfservice-ui-node-1  |       transitional: [Object],
kratos-selfservice-ui-node-1  |       adapter: [Array],
kratos-selfservice-ui-node-1  |       transformRequest: [Array],
kratos-selfservice-ui-node-1  |       transformResponse: [Array],
kratos-selfservice-ui-node-1  |       timeout: 0,
kratos-selfservice-ui-node-1  |       xsrfCookieName: 'XSRF-TOKEN',
kratos-selfservice-ui-node-1  |       xsrfHeaderName: 'X-XSRF-TOKEN',
kratos-selfservice-ui-node-1  |       maxContentLength: -1,
kratos-selfservice-ui-node-1  |       maxBodyLength: -1,
kratos-selfservice-ui-node-1  |       env: [Object],
kratos-selfservice-ui-node-1  |       validateStatus: [Function: validateStatus],
kratos-selfservice-ui-node-1  |       headers: [Object [AxiosHeaders]],
kratos-selfservice-ui-node-1  |       method: 'get',
kratos-selfservice-ui-node-1  |       url: 'http://kratos:4433//self-service/login/flows?id=e756d2cc-dd3d-492e-b697-c82e7661515f',
kratos-selfservice-ui-node-1  |       data: undefined
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     request: <ref *1> ClientRequest {
kratos-selfservice-ui-node-1  |       _events: [Object: null prototype],
kratos-selfservice-ui-node-1  |       _eventsCount: 7,
kratos-selfservice-ui-node-1  |       _maxListeners: undefined,
kratos-selfservice-ui-node-1  |       outputData: [],
kratos-selfservice-ui-node-1  |       outputSize: 0,
kratos-selfservice-ui-node-1  |       writable: true,
kratos-selfservice-ui-node-1  |       destroyed: false,
kratos-selfservice-ui-node-1  |       _last: true,
kratos-selfservice-ui-node-1  |       chunkedEncoding: false,
kratos-selfservice-ui-node-1  |       shouldKeepAlive: false,
kratos-selfservice-ui-node-1  |       maxRequestsOnConnectionReached: false,
kratos-selfservice-ui-node-1  |       _defaultKeepAlive: true,
kratos-selfservice-ui-node-1  |       useChunkedEncodingByDefault: false,
kratos-selfservice-ui-node-1  |       sendDate: false,
kratos-selfservice-ui-node-1  |       _removedConnection: false,
kratos-selfservice-ui-node-1  |       _removedContLen: false,
kratos-selfservice-ui-node-1  |       _removedTE: false,
kratos-selfservice-ui-node-1  |       strictContentLength: false,
kratos-selfservice-ui-node-1  |       _contentLength: 0,
kratos-selfservice-ui-node-1  |       _hasBody: true,
kratos-selfservice-ui-node-1  |       _trailer: '',
kratos-selfservice-ui-node-1  |       finished: true,
kratos-selfservice-ui-node-1  |       _headerSent: true,
kratos-selfservice-ui-node-1  |       _closed: false,
kratos-selfservice-ui-node-1  |       socket: [Socket],
kratos-selfservice-ui-node-1  |       _header: 'GET http://kratos:4433//self-service/login/flows?id=e756d2cc-dd3d-492e-b697-c82e7661515f HTTP/1.1\r\n' +
kratos-selfservice-ui-node-1  |         'Accept: application/json, text/plain, */*\r\n' +
kratos-selfservice-ui-node-1  |         'Cookie: csrf_token_806060ca5bf70dff3caa0e5c860002aade9d470a5a4dce73bcfa7ba10778f481=Uq2FJ3J4k+B+3S1s/qeG1XiAiGXVuCPYAjxP2g4WoqA=\r\n' +
kratos-selfservice-ui-node-1  |         'User-Agent: axios/1.6.7\r\n' +
kratos-selfservice-ui-node-1  |         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
kratos-selfservice-ui-node-1  |         'host: kratos:4433\r\n' +
kratos-selfservice-ui-node-1  |         'Connection: close\r\n' +
kratos-selfservice-ui-node-1  |         '\r\n',
kratos-selfservice-ui-node-1  |       _keepAliveTimeout: 0,
kratos-selfservice-ui-node-1  |       _onPendingData: [Function: nop],
kratos-selfservice-ui-node-1  |       agent: [Agent],
kratos-selfservice-ui-node-1  |       socketPath: undefined,
kratos-selfservice-ui-node-1  |       method: 'GET',
kratos-selfservice-ui-node-1  |       maxHeaderSize: undefined,
kratos-selfservice-ui-node-1  |       insecureHTTPParser: undefined,
kratos-selfservice-ui-node-1  |       path: 'http://kratos:4433//self-service/login/flows?id=e756d2cc-dd3d-492e-b697-c82e7661515f',
kratos-selfservice-ui-node-1  |       _ended: true,
kratos-selfservice-ui-node-1  |       res: [IncomingMessage],
kratos-selfservice-ui-node-1  |       aborted: false,
kratos-selfservice-ui-node-1  |       timeoutCb: null,
kratos-selfservice-ui-node-1  |       upgradeOrConnect: false,
kratos-selfservice-ui-node-1  |       parser: null,
kratos-selfservice-ui-node-1  |       maxHeadersCount: null,
kratos-selfservice-ui-node-1  |       reusedSocket: false,
kratos-selfservice-ui-node-1  |       host: '192.168.0.111',
kratos-selfservice-ui-node-1  |       protocol: 'http:',
kratos-selfservice-ui-node-1  |       _redirectable: [Writable],
kratos-selfservice-ui-node-1  |       [Symbol(kCapture)]: false,
kratos-selfservice-ui-node-1  |       [Symbol(kBytesWritten)]: 0,
kratos-selfservice-ui-node-1  |       [Symbol(kEndCalled)]: true,
kratos-selfservice-ui-node-1  |       [Symbol(kNeedDrain)]: false,
kratos-selfservice-ui-node-1  |       [Symbol(corked)]: 0,
kratos-selfservice-ui-node-1  |       [Symbol(kOutHeaders)]: [Object: null prototype],
kratos-selfservice-ui-node-1  |       [Symbol(kUniqueHeaders)]: null
kratos-selfservice-ui-node-1  |     },
kratos-selfservice-ui-node-1  |     data: ''
kratos-selfservice-ui-node-1  |   }
kratos-selfservice-ui-node-1  | } AxiosError: Request failed with status code 502
kratos-selfservice-ui-node-1  |     at settle (/usr/src/app/node_modules/axios/dist/node/axios.cjs:1967:12)
kratos-selfservice-ui-node-1  |     at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/dist/node/axios.cjs:3066:11)
kratos-selfservice-ui-node-1  |     at IncomingMessage.emit (node:events:525:35)
kratos-selfservice-ui-node-1  |     at endReadableNT (node:internal/streams/readable:1359:12)
kratos-selfservice-ui-node-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
kratos-selfservice-ui-node-1  |     at Axios.request (/usr/src/app/node_modules/axios/dist/node/axios.cjs:3877:41)
kratos-selfservice-ui-node-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
kratos-selfservice-ui-node-1  | {"level":"info","message":"HTTP GET /login?flow=e756d2cc-dd3d-492e-b697-c82e7661515f","meta":{"req":{"headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","accept-encoding":"gzip, deflate, br, zstd","accept-language":"zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7","connection":"keep-alive","cookie":"csrf_token_806060ca5bf70dff3caa0e5c860002aade9d470a5a4dce73bcfa7ba10778f481=Uq2FJ3J4k+B+3S1s/qeG1XiAiGXVuCPYAjxP2g4WoqA=","host":"127.0.0.1:4455","referer":"http://127.0.0.1:4455/","sec-ch-ua":"\"Chromium\";v=\"128\", \"Not;A=Brand\";v=\"24\", \"Google Chrome\";v=\"128\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Linux\"","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"same-site","sec-fetch-user":"?1","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"},"httpVersion":"1.1","method":"GET","originalUrl":"/login?flow=e756d2cc-dd3d-492e-b697-c82e7661515f","query":{"flow":"e756d2cc-dd3d-492e-b697-c82e7661515f"},"url":"/login?flow=e756d2cc-dd3d-492e-b697-c82e7661515f"},"res":{"statusCode":500},"responseTime":1295}}
kratos-selfservice-ui-node-1  | TypeError: Converting circular structure to JSON
kratos-selfservice-ui-node-1  |     --> starting at object with constructor 'ClientRequest'
kratos-selfservice-ui-node-1  |     |     property 'socket' -> object with constructor 'Socket'
kratos-selfservice-ui-node-1  |     --- property '_httpMessage' closes the circle
kratos-selfservice-ui-node-1  |     at JSON.stringify (<anonymous>)
kratos-selfservice-ui-node-1  |     at UserErrorCard$1 (/usr/src/app/node_modules/@ory/elements-markup/dist/index.umd.js:104:36900)
kratos-selfservice-ui-node-1  |     at _t (/usr/src/app/node_modules/@ory/elements-markup/dist/index.umd.js:169:3633)
kratos-selfservice-ui-node-1  |     at Nl (/usr/src/app/node_modules/@ory/elements-markup/dist/index.umd.js:169:4508)
kratos-selfservice-ui-node-1  |     at Ha (/usr/src/app/node_modules/@ory/elements-markup/dist/index.umd.js:169:7515)
kratos-selfservice-ui-node-1  |     at Wa (/usr/src/app/node_modules/@ory/elements-markup/dist/index.umd.js:169:9191)
kratos-selfservice-ui-node-1  |     at Rr (/usr/src/app/node_modules/@ory/elements-markup/dist/index.umd.js:169:8960)
kratos-selfservice-ui-node-1  |     at Ro (/usr/src/app/node_modules/@ory/elements-markup/dist/index.umd.js:169:7183)
kratos-selfservice-ui-node-1  |     at Ha (/usr/src/app/node_modules/@ory/elements-markup/dist/index.umd.js:169:7943)
kratos-selfservice-ui-node-1  |     at Wa (/usr/src/app/node_modules/@ory/elements-markup/dist/index.umd.js:169:9191)
```

### Relevant configuration

```yml
default
```

### Version

latest

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by david1542** [comment]
I'm encountering the same problem
<img width="866" alt="image" src="https://github.com/user-attachments/assets/780d267c-413c-4d40-b15c-79c9a83b04dc">
