### ISSUE TITLE
Social sign-on fails via login page for new users

### ISSUE THREAD

**Issue by anuveyatsu** [ory/kratos#431]
**Describe the bug**

If I try to use login page instead of registration with a new account, it registers the account in db, however, it fails to redirect/complete the process.

**To Reproduce**

1. Clean up the db so that you can use GitHub/Google SSO that doesn't exist in the db
2. Go to `/auth/login`
3. Select Github or Google method
4. Get `ERR_EMPTY_RESPONSE`

**Expected behavior**

Redirects to default redirect url, e.g., `/dashboard`.

**Environment**

- Kratos-selfservice-ui-node: `v0.3.0-alpha.1`
- Kratos: `v0.3.0-alpha.1`
- Environment: quickstart (docker-compose)

**Additional context**

Logs:

```bash
kratos-selfservice-ui-node_1  | No request found in URL, initializing auth flow.
kratos-selfservice-ui-node_1  | GET /auth/login 302 148 - 42.718 ms
kratos_1                      | time="2020-05-22T12:35:39Z" level=info msg="started handling request" method=GET name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49302" request=/self-service/browser/flows/login
kratos_1                      | time="2020-05-22T12:35:44Z" level=info msg="completed handling request" method=GET name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49302" request=/self-service/browser/flows/login status=302 text_status=Found took=5.4979608s
kratos-selfservice-ui-node_1  | GET /.ory/kratos/public/self-service/browser/flows/login 302 100 - 5583.624 ms
kratos_1                      | time="2020-05-22T12:35:44Z" level=info msg="started handling request" method=GET name="admin#http://kratos:4434/" remote="172.20.0.4:46460" request="/self-service/browser/flows/requests/login?request=a1386f7e-b249-40a4-9fd9-38a87329ff8a"
kratos_1                      | time="2020-05-22T12:35:44Z" level=info msg="completed handling request" method=GET name="admin#http://kratos:4434/" remote="172.20.0.4:46460" request="/self-service/browser/flows/requests/login?request=a1386f7e-b249-40a4-9fd9-38a87329ff8a" status=200 text_status=OK took=1.9646ms
kratos-selfservice-ui-node_1  | GET /auth/login?request=a1386f7e-b249-40a4-9fd9-38a87329ff8a 200 13535 - 387.953 ms
kratos-selfservice-ui-node_1  | GET /index.css 304 - - 31.221 ms
kratos-selfservice-ui-node_1  | GET /typography.css 304 - - 35.093 ms
kratos-selfservice-ui-node_1  | GET /form.css 304 - - 25.768 ms
kratos-selfservice-ui-node_1  | GET /auth.css 304 - - 33.850 ms
kratos_1                      | time="2020-05-22T12:35:47Z" level=info msg="started handling request" method=POST name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49314" request=/self-service/browser/flows/strategies/oidc/auth/a1386f7e-b249-40a4-9fd9-38a87329ff8a
kratos_1                      | time="2020-05-22T12:35:49Z" level=info msg="completed handling request" method=POST name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49314" request=/self-service/browser/flows/strategies/oidc/auth/a1386f7e-b249-40a4-9fd9-38a87329ff8a status=302 text_status=Found took=1.7090371s
kratos-selfservice-ui-node_1  | POST /.ory/kratos/public/self-service/browser/flows/strategies/oidc/auth/a1386f7e-b249-40a4-9fd9-38a87329ff8a 302 0 - 1717.150 ms
kratos_1                      | time="2020-05-22T12:35:54Z" level=info msg="started handling request" method=GET name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49320" request="/self-service/browser/flows/strategies/oidc/callback/github?code=...&state=..."
kratos_1                      | time="2020-05-22T12:35:59Z" level=debug msg="Received successful OpenID Connect callback but user is not registered. Re-initializing registration flow now." provider=github subject=...
kratos_1                      | time="2020-05-22T12:36:04Z" level=debug msg="OpenID Connect Jsonnet mapper completed." mapper_jsonnet_output="{\n   \"identity\": {\n      \"traits\": {\n         \"email\": \"your-email@mail.com\"\n      }\n   }\n}\n" mapper_jsonnet_url="file:///etc/config/kratos/oidc.github.jsonnet" oidc_claims="&{https://github.com/login/oauth/access_token ... Anuar Ustayev       https://github.com/anuveyatsu https://avatars1.githubusercontent.com/u/...?v=4  your-email@mail.com true      false 1590150887}" oidc_provider=github
kratos_1                      | time="2020-05-22T12:36:06Z" level=debug msg="A new identity has registered using self-service registration. Running post execution hooks." identity_id=d39fe51c-e8e4-4f8b-919e-0f3bdd26a45c
kratos_1                      | time="2020-05-22T12:36:07Z" level=debug msg="Post registration execution hooks completed successfully." identity_id=d39fe51c-e8e4-4f8b-919e-0f3bdd26a45c
kratos_1                      | time="2020-05-22T12:36:07Z" level=info msg="completed handling request" method=GET name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49320" request="/self-service/browser/flows/strategies/oidc/callback/github?code=...&state=... status=302 text_status=Found took=13.8210832s
kratos-selfservice-ui-node_1  | internal/streams/legacy.js:61
kratos-selfservice-ui-node_1  |       throw er; // Unhandled stream error in pipe.
kratos-selfservice-ui-node_1  |       ^
kratos-selfservice-ui-node_1  | 
kratos-selfservice-ui-node_1  | Error: socket hang up
kratos-selfservice-ui-node_1  |     at connResetException (internal/errors.js:609:14)
kratos-selfservice-ui-node_1  |     at Socket.socketOnEnd (_http_client.js:455:23)
kratos-selfservice-ui-node_1  |     at Socket.emit (events.js:333:22)
kratos-selfservice-ui-node_1  |     at endReadableNT (_stream_readable.js:1220:12)
kratos-selfservice-ui-node_1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
kratos-selfservice-ui-node_1  |   code: 'ECONNRESET'
kratos-selfservice-ui-node_1  | }
kratos-selfservice-ui-node_1  | npm ERR! code ELIFECYCLE
kratos-selfservice-ui-node_1  | npm ERR! errno 1
kratos-selfservice-ui-node_1  | npm ERR! kratos-selfservice-ui-node@0.0.1 serve: `node lib/index.js`
kratos-selfservice-ui-node_1  | npm ERR! Exit status 1
kratos-selfservice-ui-node_1  | npm ERR! 
kratos-selfservice-ui-node_1  | npm ERR! Failed at the kratos-selfservice-ui-node@0.0.1 serve script.
kratos-selfservice-ui-node_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
kratos-selfservice-ui-node_1  | 
kratos-selfservice-ui-node_1  | npm ERR! A complete log of this run can be found in:
kratos-selfservice-ui-node_1  | npm ERR!     /root/.npm/_logs/2020-05-22T12_36_07_942Z-debug.log
kratos_kratos-selfservice-ui-node_1 exited with code 1
```

From the logs you can see that the user is actually registered but then it throws an error from the node app (by the way it's another bug re error handling for which I'm creating another issue here - ory/kratos-selfservice-ui-node#44 )

**Comment by anuveyatsu** [comment]
hey @aeneasr do you have any comments about this? I could try to investigate but any help would be appreciated.

**Comment by aeneasr** [comment]
I didn't have time to work on this because I'm busy with other PRs, so any help in finding the bug is appreciated!

**Comment by aeneasr** [comment]
Could you please provide a GitHub repository with a reproducible case? You don't have to include credentials but all the configs should be there. Otherwise I can't help unfortunately because more details are missing (e.g. your JsonNet code), plus it would help with finding the cause. Thank you!

**Comment by anuveyatsu** [comment]
Hey @aeneasr this happens in `v0.3.0-alpha.1` of https://github.com/ory/kratos-selfservice-ui-node

**Comment by aeneasr** [comment]
Thank you for reconfirming - could you still please create a reproducible repository for me? As I said before it is hard for me to figure out what's going on otherwise and I can't really help then :|

**Comment by anuveyatsu** [comment]
Hey @aeneasr I've created the branch in my fork for reproducing this bug:

https://github.com/anuveyatsu/kratos/tree/bug/sso-login-vs-signup

**Comment by aeneasr** [comment]
Awesome, thank you! I'll check it out right away

**Comment by aeneasr** [comment]
I've tried all different flows (registration itself, login without previous registration) and can not reproduce the issue you observe with the code that you provided.

**Comment by aeneasr** [comment]
Here is what I did:

```
$ git clone ....
$ git checkout bug/sso-...
```

Then I created a new oauth2 account in github and updated the config file to include the client id and secret:

<img width="2672" alt="Bildschirmfoto 2020-06-18 um 12 16 38" src="https://user-images.githubusercontent.com/3372410/85008725-a49c4100-b15d-11ea-8c51-749ccf16d239.png">

Then I started the quickstart:

```
$ make quickstart
```

And went to the login page and clicked "sign up with github".

**Comment by aeneasr** [comment]
Closing due to lack of response
