### ISSUE TITLE
Segmentation fault when running kratos

### ISSUE THREAD

**Issue by marcinkoziej** [ory/kratos#685]
**Describe the bug**

Running kratos (`server` or `migrate sql`) give segmentation fault:

```
 kratos serve -c kratos.yml      
INFO[2020-09-02T20:38:24+02:00] Config file loaded successfully.              audience=application path=kratos.yml service_name=kratos service_version=
INFO[2020-09-02T20:38:24+02:00] Kratos is running migrations on every startup as DSN is memory.  audience=application service_name=ORY Kratos service_version=
INFO[2020-09-02T20:38:24+02:00] This means your data is lost when Kratos terminates.  audience=application service_name=ORY Kratos service_version=
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0xf14da3]

goroutine 1 [running]:
github.com/ory/kratos/driver.NewRegistry(0x15d84c0, 0xc000822260, 0xc0001db8c0, 0x0, 0x0, 0xc00051e800)
	/home/ory/driver/registry.go:156 +0x373
github.com/ory/kratos/driver.NewDefaultDriver(0xc000071ad0, 0x1572c40, 0xe, 0x1579790, 0x14, 0x15b03a0, 0x28, 0x7600, 0x7e00, 0xc000202600, ...)
	/home/ory/driver/driver_default.go:23 +0x83
github.com/ory/kratos/driver.MustNewDefaultDriver(0xc000071ad0, 0x1572c40, 0xe, 0x1579790, 0x14, 0x15b03a0, 0x28, 0x0, 0x7f1f70, 0xc00061fd18)
	/home/ory/driver/driver_default.go:42 +0x9a
github.com/ory/kratos/cmd.glob..func4(0x1fcdae0, 0xc0002a92e0, 0x0, 0x2)
	/home/ory/cmd/serve.go:51 +0x10c
github.com/spf13/cobra.(*Command).execute(0x1fcdae0, 0xc0002a92a0, 0x2, 0x2, 0x1fcdae0, 0xc0002a92a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1fcefe0, 0xc00061ff40, 0x78fc4a, 0x1352a39)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/ory/kratos/cmd.Execute()
	/home/ory/cmd/root.go:23 +0x31
main.main()
	/home/ory/main.go:31 +0x52
```

**Reproducing the bug**

Run: `kratos serve -c ./kratos.yml`,
environment:
DSN=postgres://kratos:PASSWORD@172.0.0.1:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
JWKS_URL=http://localhost:4456/.well-known/jwks.json
KRATOS_ADMIN_URL=http://localhost:4434/
KRATOS_BROWSER_URL=https://account.fixthestatusquo.org/.ory/kratos/public
KRATOS_PUBLIC_URL=http://localhost:4433/
PORT=4435
SECURITY_MODE=jwks

_Server logs_

```
 kratos serve -c kratos.yml      
INFO[2020-09-02T20:38:24+02:00] Config file loaded successfully.              audience=application path=kratos.yml service_name=kratos service_version=
INFO[2020-09-02T20:38:24+02:00] Kratos is running migrations on every startup as DSN is memory.  audience=application service_name=ORY Kratos service_version=
INFO[2020-09-02T20:38:24+02:00] This means your data is lost when Kratos terminates.  audience=application service_name=ORY Kratos service_version=
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0xf14da3]

goroutine 1 [running]:
github.com/ory/kratos/driver.NewRegistry(0x15d84c0, 0xc000822260, 0xc0001db8c0, 0x0, 0x0, 0xc00051e800)
	/home/ory/driver/registry.go:156 +0x373
github.com/ory/kratos/driver.NewDefaultDriver(0xc000071ad0, 0x1572c40, 0xe, 0x1579790, 0x14, 0x15b03a0, 0x28, 0x7600, 0x7e00, 0xc000202600, ...)
	/home/ory/driver/driver_default.go:23 +0x83
github.com/ory/kratos/driver.MustNewDefaultDriver(0xc000071ad0, 0x1572c40, 0xe, 0x1579790, 0x14, 0x15b03a0, 0x28, 0x0, 0x7f1f70, 0xc00061fd18)
	/home/ory/driver/driver_default.go:42 +0x9a
github.com/ory/kratos/cmd.glob..func4(0x1fcdae0, 0xc0002a92e0, 0x0, 0x2)
	/home/ory/cmd/serve.go:51 +0x10c
github.com/spf13/cobra.(*Command).execute(0x1fcdae0, 0xc0002a92a0, 0x2, 0x2, 0x1fcdae0, 0xc0002a92a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1fcefe0, 0xc00061ff40, 0x78fc4a, 0x1352a39)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/ory/kratos/cmd.Execute()
	/home/ory/cmd/root.go:23 +0x31
main.main()
	/home/ory/main.go:31 +0x52
```

_Server configuration_

This is the minimal kratos confing that has required fields and triggers segmentation fault:
kratos.yml:
```
dsn: memory

selfservice:
  default_browser_return_url: https://account.fixthestatusquo.org
identity:
  default_schema_url: file:///ory/kratos/user.json
courier:
  smtp:
    connection_uri: "tls://XXX:YYY@in-v3.mailjet.com:587/"
    from_address: "lets@fixthestatusqu.org"

```

**Expected behavior**

The server should operate normally. This configuration and set of env variables (with some modifications) work when running in docker.

**Environment**

Version:			v0.4.6-alpha.1
Build Commit:	ad90e772cf59a33b213bc0fb782959a1685d9741
Build Timestamp:	2020-07-13T12:30:38Z

Running directly under Ubuntu 20.04 Focal 
uname -a: `Linux steinem 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**

**Comment by aeneasr** [comment]
Thank you for the report - fixes welcomed :)

**Comment by marcinkoziej** [comment]
@aeneasr do you have some short instruction how to compile kratos with debug symbols included? I'm not a go dev :}

**Comment by aeneasr** [comment]
Ok then don't worry, I'll put it on my list :)

**Comment by jakhog** [comment]
This bug seems to have been fixed by 05e55f3584e20ae5d39cfda6e542d4da40d718e4. I can confirm that it was present on ad90e772cf59a33b213bc0fb782959a1685d9741, but is not present in the current master.

**Comment by jakhog** [comment]
It seems from your original post @marcinkoziej that you were trying to use Postgres for persistence, and this bug only affects the memory persistence. Maybe there is something wrong with how you have set the environment variables to configure Kratos?

**Comment by zepatrik** [comment]
DSN is defined twice, as env var and in the config.

**Comment by zepatrik** [comment]
I'm pretty confident that https://github.com/ory/kratos/commit/05e55f3584e20ae5d39cfda6e542d4da40d718e4 fixed this issue indeed, therefore I'm closing this. Thanks @jakhog and @marcinkoziej
