### ISSUE TITLE
Docs Bug: sidebar.json messed up

### ISSUE THREAD

**Issue by vinckr** [ory/kratos#967]
**Describe the bug**

sidebar.json has multiple CLI reference sections added to the top. It seems to be adding with each template update. 
 ```
  "Reference": [
    {
      "items": [
        "cli/kratos", 
        "cli/kratos-hashers", 
        "cli/kratos-hashers-argon2", 
        "cli/kratos-hashers-argon2-calibrate", 
        "cli/kratos-identities", 
        "cli/kratos-identities-delete", 
        "cli/kratos-identities-get", 
        "cli/kratos-identities-import", 
        "cli/kratos-identities-list", 
        "cli/kratos-identities-patch", 
        "cli/kratos-identities-validate", 
        "cli/kratos-jsonnet", 
        "cli/kratos-jsonnet-format", 
        "cli/kratos-jsonnet-lint", 
        "cli/kratos-migrate", 
        "cli/kratos-migrate-sql", 
        "cli/kratos-remote", 
        "cli/kratos-remote-status", 
        "cli/kratos-remote-version", 
        "cli/kratos-serve", 
        "cli/kratos-version"
```

**Reproducing the bug**

Try to build the docs 

npm i 
npm start

**Fix**
This version of the sidebar is working.
https://github.com/ory/kratos/blob/5aaef917db8b85890a9b52e701106b27fbdf1c0c/docs/sidebar.json

**Additional context**
```

 > docusaurus-template@0.0.0 start /Users/vinckr/Projects/kratos/docs
> docusaurus start

Starting the development server...
SyntaxError: /Users/vinckr/Projects/kratos/docs/sidebar.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1151:22)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/vinckr/Projects/kratos/docs/contrib/sidebar.js:30:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at Object.module.exports [as default] (/Users/vinckr/Projects/kratos/docs/node_modules/import-fresh/index.js:32:59)
    at Object.loadSidebars (/Users/vinckr/Projects/kratos/docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars.js:131:47)
    at loadVersion (/Users/vinckr/Projects/kratos/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:98:45)
    at Array.map (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docusaurus-template@0.0.0 start: `docusaurus start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docusaurus-template@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by aeneasr** [comment]
https://github.com/ory/kratos/issues/951
